### ISSUE TITLE
Core dump using uvaialign to align genomes

### ISSUE THREAD

**Issue by flashton2003** [quadram-institute-bioscience/uvaia#1] opened 2022-04-07 10:57 UTC
Hello,

I'm trying to use uvaialign to align 316 SC2 genomes (input file is [here](https://www.dropbox.com/s/ogcfcpi986vihbm/all.fasta?dl=0)).

Command line is:

`uvaialign -r ~/COVID/reference_genome/2022.04.06/NC_045512.2.fasta all.fasta > aln.fa`

It partially completes and then just `Illegal instruction (core dumped)`

Installed via conda, on an Ubuntu 20 system.

**Comment by leomrtns** [comment] 2022-04-07 11:38
Hi! yes I can confirm the same error on my machine using conda. Thank you for reporting (and for trying uvaia!).
After compiling from source it worked &mdash; on my machine :wink: .  I've been working quite often on the code so the conda version should be outdated. I'll bump the conda and hope it's not a glibc version issue.

**Comment by leomrtns** [comment] 2022-04-07 17:56
It will take a bit longer for the conda version to be updated (fixing silly bugs, and adding xz compression to uvaialign). In the meanwhile here is a conda package which should work: 
[uvaia-2.0.0-h9bf148f_0.tar.bz2.gz](https://github.com/quadram-institute-bioscience/uvaia/files/8445196/uvaia-2.0.0-h9bf148f_0.tar.bz2.gz) I had to compress it with gzip on top of the default bz2, since github doesn't recognise bz2. You can try it with `conda install --use-local uvaia-2.0.0-h9bf148f_0.tar.bz2` 

This package worked on a few VMs, but one never knows!

**Comment by flashton2003** [comment] 2022-04-07 18:03
Ok thanks Leo.

I’m going to have to try a different approach for now for unrelated
reasons, but will circle back to this if I need to.

**Comment by leomrtns** [comment] 2022-06-30 21:34
The new conda version should work on this dataset. I'll close the issue but feel free to re-open it.

**Closed as completed by leomrtns** 2022-06-30 21:34 UTC
